language: node_js

node_js:
    - "6"
    - "8"
    - "9"

cache: yarn

script:
    - npm run lint
    - npm run build

jobs:
    include:
        - stage: Publish docs
          if: type = push AND branch = master AND fork = false
          script: scripts/travis/publishDocs.sh

