blank_issues_enabled: false
contact_links:
    -
        name: â“ Support Question
        about: "If you have a question ğŸ’¬, please ask it on the Twitch API Libraries Discord in the #twurple channel!"
        url: "https://discord.gg/b9ZqMfz"
