blank_issues_enabled: false
contact_links:
    -
        name: â“ Support Question
        about: "If you have a question ğŸ’¬, please ask it on the Twitch API Discord in the #twitch-js channel!"
        url: "https://discord.gg/b9ZqMfz"
