name: Node.js CI

on:
  push:
    branches: [ main, versions/** ]
  pull_request:
    branches: [ main, versions/** ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js 18
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - run: yarn
      - run: yarn run build
      - run: yarn run lint
      - run: yarn run prettier:check
      - name: Archive build assets
        run: tar cvf build-result.tar packages/*/lib packages/*/es node_modules/.cache/tsukuru
      - name: Save build assets
        uses: actions/upload-artifact@v3
        with:
          name: build-result
          path: build-result.tar
  test:
    strategy:
      matrix:
        node-version: [ 20, 18, 16 ]

    needs: [ build ]
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - run: yarn
      - name: Load build assets
        uses: actions/download-artifact@v3
        with:
          name: build-result
      - name: Unarchive build assets
        run: tar xvf build-result.tar
      - run: yarn test
  docs:
    if: ${{ github.event_name == 'push' }}
    needs: [ build, test ]
    runs-on: ubuntu-latest
    concurrency:
      group: docs-${{ github.ref }}
      cancel-in-progress: true
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js 18
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - run: yarn
      - name: Load build assets
        uses: actions/download-artifact@v3
        with:
          name: build-result
      - name: Unarchive build assets
        run: tar xvf build-result.tar
      - env:
          BUILD_NUMBER: ${{ github.run_number }}
          REPO_USER: ${{ github.repository_owner }}
          GIT_REF: ${{ github.ref }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: scripts/github/publishDocs.sh
